version: "3.3"
services:
  consul:
    environment:
      CONSUL_BIND_INTERFACE: eth0
    image: "consul:1.3.0"
    ports:
      - "8500:8500"
  frontend:
    environment:
      SPRING_CLOUD_CONSUL_HOST: consul
    image: "alexandreroman/number2words-frontend"
    ports:
    - "8080:8080"
  backend:
    environment:
      SPRING_CLOUD_CONSUL_HOST: consul
    image: "alexandreroman/number2words-backend"
